name: 'Deploy Infrastructure'

on:
  push:
    branches:
      - main

jobs: 
  AzureBicepDeploy:
    name: 'AzureBicepDeploy'
    runs-on: ubuntu-latest
    environment: production
 
    steps:
    - uses: actions/checkout@v2
 
    - uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
 
    - name: Azure Bicep Build
      run: |
        az bicep build --file main.bicep

    - name: Validate Azure Bicep
      uses: Azure/arm-deploy@v1
      with:
        scope: subscription
        region: australiaeast
        template: main.bicep
        deploymentName: todoapp
        deploymentMode: validate
        parameters: githubToken=${{ secrets.PAT_GITHUB }}

    - name: Preview Azure Bicep
      run: |
        az deployment sub what-if \
          --location australiaeast \
          --template-file main.bicep \
          --parameters githubToken=${{ secrets.PAT_GITHUB }}
 
    - name: Deploy Azure Bicep
      uses: Azure/arm-deploy@v1
      with:
        scope: subscription
        region: australiaeast
        template: main.bicep
        deploymentName: todoapp
        parameters: githubToken=${{ secrets.PAT_GITHUB }}